{{- if .Values.authentik.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "authentik.fullname" . }}-authentik
spec:
  ports:
  - name: http
    port: 80
    targetPort: 9000
  - name: https
    port: 443
    targetPort: 9443
  selector:
    app.kubernetes.io/name: authentik
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}